/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWcNewsRouteImport } from './routes/api/public/wc-news'
import { Route as ApiPublicWcLiveRouteImport } from './routes/api/public/wc-live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWcNewsRoute = ApiPublicWcNewsRouteImport.update({
  id: '/api/public/wc-news',
  path: '/api/public/wc-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWcLiveRoute = ApiPublicWcLiveRouteImport.update({
  id: '/api/public/wc-live',
  path: '/api/public/wc-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/wc-live': typeof ApiPublicWcLiveRoute
  '/api/public/wc-news': typeof ApiPublicWcNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/wc-live': typeof ApiPublicWcLiveRoute
  '/api/public/wc-news': typeof ApiPublicWcNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/wc-live': typeof ApiPublicWcLiveRoute
  '/api/public/wc-news': typeof ApiPublicWcNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/wc-live' | '/api/public/wc-news'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/wc-live' | '/api/public/wc-news'
  id: '__root__' | '/' | '/api/public/wc-live' | '/api/public/wc-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWcLiveRoute: typeof ApiPublicWcLiveRoute
  ApiPublicWcNewsRoute: typeof ApiPublicWcNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wc-news': {
      id: '/api/public/wc-news'
      path: '/api/public/wc-news'
      fullPath: '/api/public/wc-news'
      preLoaderRoute: typeof ApiPublicWcNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wc-live': {
      id: '/api/public/wc-live'
      path: '/api/public/wc-live'
      fullPath: '/api/public/wc-live'
      preLoaderRoute: typeof ApiPublicWcLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWcLiveRoute: ApiPublicWcLiveRoute,
  ApiPublicWcNewsRoute: ApiPublicWcNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
